import { getSupabaseClient } from '/workspace/projects/src/storage/database/supabase-client';

interface JobProfile {
  profile_name: string;
  category: string;
  description: string;
  professional_skills: string;
  certificate_requirements: string;
  innovation_ability: number;
  learning_ability: number;
  pressure_resistance: number;
  communication_ability: number;
  internship_requirement: string;
  education_requirement: string;
  work_experience_requirement: string;
  salary_range: string;
  career_direction: string;
  core_qualifications: string;
  tools_requirement: string;
}

// 继续创建更多岗位画像
const additionalProfiles: JobProfile[] = [
  {
    profile_name: '运维工程师',
    category: '技术类',
    description: '负责服务器运维、系统监控、故障排查，保障业务系统7x24小时稳定运行。',
    professional_skills: 'Linux系统管理、Nginx/Apache配置、Docker容器编排、Kubernetes、Shell/Python脚本、监控系统（Prometheus/Grafana）、日志分析、自动化运维',
    certificate_requirements: 'Linux运维工程师认证、RHCSA/RHCE、阿里云ACE认证',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 4,
    communication_ability: 3,
    internship_requirement: '有Linux运维或服务器管理实习经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '8000-18000元/月',
    career_direction: '运维架构师、SRE工程师、DevOps工程师、技术总监',
    core_qualifications: '故障应急能力、系统思维、安全意识、持续学习',
    tools_requirement: 'Linux、Git、Docker、K8s、Ansible、Prometheus',
  },
  {
    profile_name: '算法工程师',
    category: '技术类',
    description: '负责机器学习算法研发、模型优化、数据挖掘，推动AI技术落地应用。',
    professional_skills: 'Python/C++、TensorFlow/PyTorch、机器学习/深度学习、NLP/CV算法、数据挖掘、算法优化、模型部署、大数据处理',
    certificate_requirements: '深度学习工程师认证、Kaggle竞赛证书',
    innovation_ability: 5,
    learning_ability: 5,
    pressure_resistance: 3,
    communication_ability: 3,
    internship_requirement: '有算法研究或AI项目实习经验，发表过论文优先',
    education_requirement: '硕士及以上',
    work_experience_requirement: '1-5年',
    salary_range: '15000-40000元/月',
    career_direction: '算法专家、AI架构师、首席科学家、创业者',
    core_qualifications: '数学功底扎实、算法研究能力、工程落地能力',
    tools_requirement: 'Python、TensorFlow、PyTorch、Spark、Hadoop',
  },
  {
    profile_name: '数据分析师',
    category: '技术类',
    description: '负责数据分析、报表开发、业务洞察，通过数据驱动企业决策。',
    professional_skills: 'SQL查询、Python/R数据分析、Excel高级应用、数据可视化（Tableau/PowerBI）、统计学基础、BI报表开发、业务分析能力',
    certificate_requirements: '数据分析证书、Tableau认证',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 2,
    communication_ability: 4,
    internship_requirement: '有数据分析实习或商业分析项目经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '8000-18000元/月',
    career_direction: '高级分析师、数据产品经理、数据科学家、数据总监',
    core_qualifications: '数据敏感度、逻辑思维、业务理解、沟通表达',
    tools_requirement: 'SQL、Python/R、Tableau、PowerBI、Excel',
  },
  {
    profile_name: '项目经理',
    category: '管理类',
    description: '负责项目规划、执行、监控与收尾，协调资源确保项目按时按质交付。',
    professional_skills: '项目管理、敏捷/Scrum方法论、WBS分解、风险管理、干系人管理、团队协调、资源调配、进度控制',
    certificate_requirements: 'PMP认证、软考高项、ACP认证',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 5,
    communication_ability: 5,
    internship_requirement: '有项目管理实习或学生会/社团活动组织经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '2-5年',
    salary_range: '12000-25000元/月',
    career_direction: '高级项目经理、项目总监、PMO负责人、COO',
    core_qualifications: '统筹协调能力、风险管理意识、沟通谈判能力、抗压能力',
    tools_requirement: 'Project、JIRA、Confluence、钉钉/飞书',
  },
  {
    profile_name: '新媒体运营',
    category: '运营类',
    description: '负责新媒体内容创作、账号运营、粉丝互动，提升品牌影响力。',
    professional_skills: '内容策划、短视频制作、公众号运营、小红书/抖音运营、热点捕捉、文案写作、数据分析、粉丝运营',
    certificate_requirements: '新媒体运营师证书、短视频运营证书',
    innovation_ability: 5,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 4,
    internship_requirement: '有自媒体运营经验，有爆款内容案例优先',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '6000-15000元/月',
    career_direction: '新媒体主管、内容总监、KOL、MCN机构创始人',
    core_qualifications: '网感强、创意策划、内容创作、数据分析',
    tools_requirement: '剪映/PR、PS、排版工具、数据分析工具',
  },
  {
    profile_name: '电商运营',
    category: '运营类',
    description: '负责电商平台店铺运营、营销推广、客户服务，提升店铺销量和转化率。',
    professional_skills: '淘宝/京东/拼多多运营、直通车/钻展投放、店铺数据分析、活动策划、客服管理、供应链协调、爆款打造',
    certificate_requirements: '电商运营师证书',
    innovation_ability: 4,
    learning_ability: 4,
    pressure_resistance: 4,
    communication_ability: 4,
    internship_requirement: '有电商运营实习或自己经营过网店',
    education_requirement: '大专及以上',
    work_experience_requirement: '1-3年',
    salary_range: '6000-15000元/月+提成',
    career_direction: '电商主管、电商经理、店铺合伙人、创业者',
    core_qualifications: '数据分析能力、营销敏感度、执行力',
    tools_requirement: '电商后台、生意参谋、Excel、数据分析工具',
  },
  {
    profile_name: '物流专员',
    category: '供应链类',
    description: '负责仓储管理、物流调度、运输跟踪，优化物流成本和效率。',
    professional_skills: '仓储管理、物流调度、WMS系统操作、运输跟踪、成本控制、供应商管理、数据统计、异常处理',
    certificate_requirements: '物流师证书',
    innovation_ability: 3,
    learning_ability: 3,
    pressure_resistance: 3,
    communication_ability: 4,
    internship_requirement: '有物流或仓储实习经验',
    education_requirement: '大专及以上',
    work_experience_requirement: '1-3年',
    salary_range: '5000-10000元/月',
    career_direction: '物流主管、物流经理、供应链总监',
    core_qualifications: '细心严谨、成本意识、协调能力',
    tools_requirement: 'WMS系统、Office、物流跟踪工具',
  },
  {
    profile_name: '质量管理',
    category: '技术类',
    description: '负责质量体系建立、质量检验、不合格品处理，推动质量改进。',
    professional_skills: 'ISO9001体系、质量检验、QC手法、质量分析、不合格品处理、质量改进、供应商质量管理、检测设备使用',
    certificate_requirements: '质量工程师证书、ISO内审员证书',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 4,
    internship_requirement: '有质量相关实习经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '6000-12000元/月',
    career_direction: '质量主管、质量经理、质量总监',
    core_qualifications: '严谨细致、数据分析、持续改进',
    tools_requirement: '检测设备、Office、质量分析工具',
  },
  {
    profile_name: '法务专员',
    category: '职能类',
    description: '负责合同审核、法律咨询、纠纷处理，防范企业法律风险。',
    professional_skills: '合同审核、法律咨询、法律法规、劳动法、知识产权、诉讼处理、合规审查、法律文书撰写',
    certificate_requirements: '法律职业资格证书、企业法律顾问证书',
    innovation_ability: 2,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 4,
    internship_requirement: '有律所或企业法务实习经验',
    education_requirement: '本科及以上（法学专业）',
    work_experience_requirement: '1-3年',
    salary_range: '6000-15000元/月',
    career_direction: '法务主管、法务经理、法务总监',
    core_qualifications: '法律专业扎实、逻辑严谨、保密意识',
    tools_requirement: '法律数据库、Office、合同管理系统',
  },
  {
    profile_name: '采购专员',
    category: '供应链类',
    description: '负责供应商开发、采购执行、价格谈判，优化采购成本和供应链效率。',
    professional_skills: '供应商开发、采购流程、价格谈判、合同管理、供应商评估、成本分析、市场调研、供应链协同',
    certificate_requirements: '采购师证书、CPSM认证',
    innovation_ability: 3,
    learning_ability: 3,
    pressure_resistance: 3,
    communication_ability: 5,
    internship_requirement: '有采购或供应链实习经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '5000-12000元/月',
    career_direction: '采购主管、采购经理、供应链总监',
    core_qualifications: '谈判能力、成本意识、供应商管理',
    tools_requirement: 'ERP系统、Office、比价工具',
  },
  {
    profile_name: '行政专员',
    category: '职能类',
    description: '负责日常行政事务、办公管理、后勤保障，支撑企业正常运转。',
    professional_skills: '日程管理、会议组织、办公采购、车辆管理、资产管理、后勤协调、文书撰写、印章管理',
    certificate_requirements: '行政管理师证书',
    innovation_ability: 2,
    learning_ability: 3,
    pressure_resistance: 3,
    communication_ability: 5,
    internship_requirement: '有行政或办公室助理实习经验',
    education_requirement: '大专及以上',
    work_experience_requirement: '不限',
    salary_range: '4000-8000元/月',
    career_direction: '行政主管、行政经理、行政总监',
    core_qualifications: '细心周到、服务意识、沟通协调',
    tools_requirement: 'Office、OA系统、钉钉/飞书',
  },
  {
    profile_name: '网络工程师',
    category: '技术类',
    description: '负责网络架构设计、设备配置、安全防护，保障网络安全稳定运行。',
    professional_skills: '网络规划、路由器/交换机配置、TCP/IP协议、防火墙配置、网络安全、WLAN部署、故障诊断、网络监控',
    certificate_requirements: '思科/华为认证网络工程师HCIP/CCNP',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 3,
    internship_requirement: '有网络运维或IT实习经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '7000-15000元/月',
    career_direction: '网络架构师、安全工程师、CTO',
    core_qualifications: '技术扎实、安全意识、故障排查',
    tools_requirement: '网络设备、监控工具、Sniffer',
  },
  {
    profile_name: '机械工程师',
    category: '技术类',
    description: '负责机械产品设计、工艺编制、技术支持，推动产品研发与制造。',
    professional_skills: '机械设计、SolidWorks/AutoCAD、力学分析、加工工艺、公差配合、装配调试、技术文档、专利撰写',
    certificate_requirements: '机械工程师职称证书、CAD证书',
    innovation_ability: 4,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 3,
    internship_requirement: '有机械设计或制造企业实习经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '6000-14000元/月',
    career_direction: '机械主管、机械经理、研发总监',
    core_qualifications: '专业扎实、设计能力、动手实践',
    tools_requirement: 'SolidWorks、AutoCAD、ANSYS、Office',
  },
  {
    profile_name: '电气工程师',
    category: '技术类',
    description: '负责电气系统设计、PLC编程、调试维护，保障设备电气系统稳定运行。',
    professional_skills: '电气设计、PLC编程（西门子/三菱）、电路图绘制、电气调试、HMI开发、变频器控制、电气标准、安全规范',
    certificate_requirements: '电气工程师职称证书、电工证',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 3,
    internship_requirement: '有电气设计或PLC编程实习经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '7000-15000元/月',
    career_direction: '电气主管、电气经理、研发工程师',
    core_qualifications: '电气专业扎实、逻辑思维、安全意识',
    tools_requirement: 'CAD E、PLC编程软件、仿真工具',
  },
  {
    profile_name: '建筑工程师',
    category: '建筑类',
    description: '负责建筑工程施工技术管理、质量控制、安全监督，保障项目顺利实施。',
    professional_skills: '施工技术、图纸审核、施工组织设计、质量控制、安全管理、进度协调、竣工验收、工程造价基础',
    certificate_requirements: '建造师证书、工程师职称证书',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 4,
    communication_ability: 4,
    internship_requirement: '有建筑施工或监理实习经验',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-5年',
    salary_range: '7000-18000元/月',
    career_direction: '项目经理、总监、甲方代表',
    core_qualifications: '专业扎实、现场管理、协调能力',
    tools_requirement: 'CAD、Project、品茗BIM',
  },
  {
    profile_name: '金融分析师',
    category: '金融类',
    description: '负责金融市场分析、投资研究、风险管理，为投资决策提供依据。',
    professional_skills: '财务报表分析、估值建模、行业研究、风险管理、宏观经济分析、投资报告撰写、金融产品知识',
    certificate_requirements: 'CFA证书、证券/基金从业资格证',
    innovation_ability: 3,
    learning_ability: 5,
    pressure_resistance: 4,
    communication_ability: 4,
    internship_requirement: '有金融机构实习或研究报告撰写经验',
    education_requirement: '本科及以上（金融/经济专业）',
    work_experience_requirement: '1-3年',
    salary_range: '10000-25000元/月',
    career_direction: '高级分析师、投资总监、CFO',
    core_qualifications: '财务分析能力、行业洞察、逻辑思维',
    tools_requirement: 'Wind、Excel、Python、Bloomberg',
  },
  {
    profile_name: '翻译',
    category: '语言类',
    description: '负责文档翻译、口译服务、语言润色，搭建跨语言沟通桥梁。',
    professional_skills: '中英互译（或其他语种）、专业术语、翻译软件（Trados）、口语表达、文案润色、文化理解、行业专业知识',
    certificate_requirements: 'CATTI翻译资格证、英语专八、其他语种等级证书',
    innovation_ability: 3,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 4,
    internship_requirement: '有翻译实习或海外交流经历',
    education_requirement: '本科及以上（外语专业）',
    work_experience_requirement: '1-3年',
    salary_range: '6000-15000元/月',
    career_direction: '高级翻译、同声传译、自由译者',
    core_qualifications: '语言功底扎实、知识面广、表达流畅',
    tools_requirement: 'Trados、Office、有道词典',
  },
  {
    profile_name: '游戏开发工程师',
    category: '技术类',
    description: '负责游戏客户端/服务端开发，实现游戏玩法和功能。',
    professional_skills: 'Unity/UE4引擎、C#/C++/Lua编程、游戏逻辑开发、网络同步、性能优化、Shader编写、美术协作',
    certificate_requirements: 'Unity认证开发者',
    innovation_ability: 5,
    learning_ability: 4,
    pressure_resistance: 3,
    communication_ability: 3,
    internship_requirement: '有游戏项目开发经验，有个人作品优先',
    education_requirement: '本科及以上',
    work_experience_requirement: '1-3年',
    salary_range: '10000-25000元/月',
    career_direction: '游戏主程序、技术总监、创业者',
    core_qualifications: '游戏热情、技术扎实、创意能力',
    tools_requirement: 'Unity/UE4、Git、Perforce',
  },
];

async function main() {
  const client = getSupabaseClient();

  console.log('开始导入更多岗位画像...');

  const { error } = await client.from('job_profiles').insert(additionalProfiles);
  if (error) {
    console.error('导入失败:', error.message);
    throw new Error(error.message);
  }

  console.log(`成功导入 ${additionalProfiles.length} 个岗位画像！`);

  // 统计总数
  const { count } = await client.from('job_profiles').select('*', { count: 'exact', head: true });
  console.log(`数据库中现有岗位画像总数: ${count} 个`);
}

main().catch(console.error);
